
#ifndef TELEPHONEBOOKVIEW_EXPORT_H
#define TELEPHONEBOOKVIEW_EXPORT_H

#ifdef TELEPHONEBOOKVIEW_STATIC_DEFINE
#  define TELEPHONEBOOKVIEW_EXPORT
#  define TELEPHONEBOOKVIEW_NO_EXPORT
#else
#  ifndef TELEPHONEBOOKVIEW_EXPORT
#    ifdef TelephoneBookView_EXPORTS
        /* We are building this library */
#      define TELEPHONEBOOKVIEW_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define TELEPHONEBOOKVIEW_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef TELEPHONEBOOKVIEW_NO_EXPORT
#    define TELEPHONEBOOKVIEW_NO_EXPORT 
#  endif
#endif

#ifndef TELEPHONEBOOKVIEW_DEPRECATED
#  define TELEPHONEBOOKVIEW_DEPRECATED __declspec(deprecated)
#endif

#ifndef TELEPHONEBOOKVIEW_DEPRECATED_EXPORT
#  define TELEPHONEBOOKVIEW_DEPRECATED_EXPORT TELEPHONEBOOKVIEW_EXPORT TELEPHONEBOOKVIEW_DEPRECATED
#endif

#ifndef TELEPHONEBOOKVIEW_DEPRECATED_NO_EXPORT
#  define TELEPHONEBOOKVIEW_DEPRECATED_NO_EXPORT TELEPHONEBOOKVIEW_NO_EXPORT TELEPHONEBOOKVIEW_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef TELEPHONEBOOKVIEW_NO_DEPRECATED
#    define TELEPHONEBOOKVIEW_NO_DEPRECATED
#  endif
#endif

#endif /* TELEPHONEBOOKVIEW_EXPORT_H */
