
#ifndef TELEPHONEBOOKMODEL_EXPORT_H
#define TELEPHONEBOOKMODEL_EXPORT_H

#ifdef TELEPHONEBOOKMODEL_STATIC_DEFINE
#  define TELEPHONEBOOKMODEL_EXPORT
#  define TELEPHONEBOOKMODEL_NO_EXPORT
#else
#  ifndef TELEPHONEBOOKMODEL_EXPORT
#    ifdef TelephoneBookModel_EXPORTS
        /* We are building this library */
#      define TELEPHONEBOOKMODEL_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define TELEPHONEBOOKMODEL_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef TELEPHONEBOOKMODEL_NO_EXPORT
#    define TELEPHONEBOOKMODEL_NO_EXPORT 
#  endif
#endif

#ifndef TELEPHONEBOOKMODEL_DEPRECATED
#  define TELEPHONEBOOKMODEL_DEPRECATED __declspec(deprecated)
#endif

#ifndef TELEPHONEBOOKMODEL_DEPRECATED_EXPORT
#  define TELEPHONEBOOKMODEL_DEPRECATED_EXPORT TELEPHONEBOOKMODEL_EXPORT TELEPHONEBOOKMODEL_DEPRECATED
#endif

#ifndef TELEPHONEBOOKMODEL_DEPRECATED_NO_EXPORT
#  define TELEPHONEBOOKMODEL_DEPRECATED_NO_EXPORT TELEPHONEBOOKMODEL_NO_EXPORT TELEPHONEBOOKMODEL_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef TELEPHONEBOOKMODEL_NO_DEPRECATED
#    define TELEPHONEBOOKMODEL_NO_DEPRECATED
#  endif
#endif

#endif /* TELEPHONEBOOKMODEL_EXPORT_H */
